# Dockerfile.producer
FROM python:3.10-slim

# Install dependencies
RUN pip install --no-cache-dir faker confluent_kafka

# Set working directory
WORKDIR /app

# Copy main.py script into the container
COPY main.py .

